name: "everything test"
on:
    pull_request:
        types: [ready_for_review, closed]
        branches:
            - main
    issues:
        types: [opened, edited, reopened, closed, labeled]

jobs:
    automate:
        runs-on: ubuntu-latest
        steps:
            - uses: polinetworkorg/clickup-integration-action@main
              with:
                  problem_list_id: 900400393970
                  feature_list_id: 900400393973
                  clickup_api_key: ${{ secrets.CLICKUP_TOKEN }}
