name: "everything test"
on:
    push:
    pull_request:
        types: [opened, reopened, closed]
        branches:
            - main
    issues:
        types: [opened, edited, reopened, closed]

jobs:
    automate:
        runs-on: ubuntu-latest
        steps:
            - uses: toto04/action-test@main
              with:
                  problem_list_id: 900400393970
                  feature_list_id: 900400393973
                  clickup_api_key: ${{ secrets.CLICKUP_TOKEN }}
