name: "everything test"
on:
    push:
    pull_request:
        types: [opened, reopened, closed]
        branches:
            - main
    issues:
        types: [opened, edited, reopened, closed]

jobs:
    automate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: toto04/action-test@main
              with:
                  problem_list_id: 210431256
                  feature_list_id: 900400324463
                  clickup_api_key: ${{ secrets.CLICKUP_TOKEN }}
